### PR TITLE
Too low backoff limit breaks backup with B2

### PR DESCRIPTION
**Pull request by DreamFlasher**
Fixes https://github.com/gilbertchen/duplicacy/issues/425

### CODE REVIEW

**Comment by gilbertchen** [comment]
This won't work -- the backoff mechanism should be modified for such a high number of retries.

**Comment by DreamFlasher** [comment]
Well it works for me, as described in #425. Can you at least make the backoff limit configurable? I always have to patch and rebuild the code myself without that.

**Comment by TheBestPessimist** [comment]
@DreamFlasher you already requested that in #423  (and i totally approve!)

**Comment by DreamFlasher** [comment]
@TheBestPessimist Thanks. As issue #423 was never adressed but instead my PR here was closed I figured I write it again.

**Pull request closed without merging**
