### PR TITLE
Acknowledge malware/spam warnings from GCD

### PR DESCRIPTION
**Pull request by s4y**
If Google thinks that a file is malware or spam (which can happen
spuriously to blobs of encrypted data), it will prevent the initial
download and return an error with reason "cannotDownloadAbusiveFile".
The API expects a program to prompt the user in this case and then,
optionally, let them bypass it.

Ideally duplicacy should prompt, but this patch just logs a warning.

When I printed `err.(*googleapi.Error)`, its `Errors` field was empty,
hence the sketchy string matching. It's possible that I did something
wrong, though.

Fixes issue #443.

### CODE REVIEW

**Comment by jt70471** [comment]
This should be a command line switch in my opinion to leave it to the user whether they want to download potentially dangerous content.

**Comment by gilbertchen** [comment]
Do you still keep the chunk that caused the error?  If so do you mind sharing the file with me so I can reproduce the error myself?

**Comment by s4y** [comment]
@gilbertchen Sure thing. I made it public under the assumption that the chunk is encrypted and doesn't leak any information on its own, but let me know if that's not the case and I'll lock it down:

https://drive.google.com/file/d/1BAn6XfBFWTjmH5Vjn7OgW25pOo-GKuzZ/view

**Comment by TowerBR** [comment]
@s4y , I tried to download the file out of curiosity, but ...

> "Sorry, this file is infected with a virus
> Only the owner is allowed to download infected files."

Have you tried uploading the file to www.virustotal.com to see what the various antivirus programs say?

**Comment by gilbertchen** [comment]
I was able to download the file by creating a copy in Google Drive and then downloading the copy.

virustotal.com results: https://www.virustotal.com/#/file/a99631f46c2e2458cc0b6c309dcc8bac64ada55422e676f172b78d49ee5e8b91/detection

**Comment by s4y** [comment]
And, just to make sure, the file does look like the expected Duplicacy encrypted noise, right?

**Comment by gilbertchen** [comment]
@s4y yes, that chunk file is encrypted by a randomly generated key stored in your `config` file so no one else can decrypt it.

**Comment by gilbertchen** [comment]
Thank you for the fix.  The string matching is fine as it looks like the Google Drive library code doesn't unmarshal the body before returning the error.

**Pull request merged**
