### PR TITLE
Fix "Failed to fossilize chunk" errors in wasabi backend

### LINKED ISSUE #458: wasabi backend fails with "Failed to fossilize chunk" when pruning (fixed with pull request)
Using dfdbfed on Ubuntu 16.04.4.

When pruning, the Wasabi backend consistently fails with "Failed to fossilize chunk".  It reports a 404 Not Found, however the chunk is present on the storage backend.

Executing the same command again repeats the process, except failing on fossilizing a different chunk.  Each time fails on a different chunk, with the previous chunks remaining orphaned on storage.

Swapping back to the s3 backend and the prune completed without errors.

Attached is a full log showing repeated consecutive invocations failing on different chunks, plus the final invocation with the s3 backend which was successful on first attempt.

Here's an excerpt from one of the failed runs:

```
# duplicacy -d -log prune -keep 1:1 -keep 5:7 -keep 15:30 -keep 30:180 -keep 0:360 | tee -a /var/log/duplicacy.log
2018-07-11 21:20:03.673 INFO STORAGE_SET Storage set to wasabi://us-east-1@s3.wasabisys.com/redacted
2018-07-11 21:20:03.673 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_WASABI_KEY
2018-07-11 21:20:03.673 DEBUG PASSWORD_PREFERENCE Reading wasabi_key from preferences
2018-07-11 21:20:03.673 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_WASABI_SECRET
2018-07-11 21:20:03.673 DEBUG PASSWORD_PREFERENCE Reading wasabi_secret from preferences
2018-07-11 21:20:03.673 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_WASABI_KEY
2018-07-11 21:20:03.674 DEBUG PASSWORD_PREFERENCE Reading wasabi_key from preferences
2018-07-11 21:20:03.674 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_WASABI_SECRET
2018-07-11 21:20:03.674 DEBUG PASSWORD_PREFERENCE Reading wasabi_secret from preferences
2018-07-11 21:20:03.674 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_PASSWORD
2018-07-11 21:20:03.674 DEBUG PASSWORD_PREFERENCE Reading password from preferences
2018-07-11 21:20:03.982 TRACE CONFIG_ITERATIONS Using 16384 iterations for key derivation
2018-07-11 21:20:04.053 DEBUG STORAGE_NESTING Chunk read levels: [1], write level: 1
2018-07-11 21:20:04.067 INFO CONFIG_INFO Compression level: 100
2018-07-11 21:20:04.067 INFO CONFIG_INFO Average chunk size: 4194304
2018-07-11 21:20:04.067 INFO CONFIG_INFO Maximum chunk size: 16777216
2018-07-11 21:20:04.067 INFO CONFIG_INFO Minimum chunk size: 1048576
2018-07-11 21:20:04.067 INFO CONFIG_INFO Chunk seed: 50a4d4a8aaa118dbbceed243e071d24fd799d32ba31efe8f033a391fe1d2f1c7
2018-07-11 21:20:04.067 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_PASSWORD
2018-07-11 21:20:04.067 DEBUG PASSWORD_PREFERENCE Reading password from preferences
2018-07-11 21:20:04.067 DEBUG DELETE_PARAMETERS id: backup, revisions: [], tags: [], retentions: [1:1 5:7 15:30 30:180 0:360], exhaustive: false, exclusive: false, dryrun: false, deleteOnly: false, collectOnl
y: false
2018-07-11 21:20:04.068 INFO RETENTION_POLICY Keep 1 snapshot every 1 day(s) if older than 1 day(s)
2018-07-11 21:20:04.068 TRACE SNAPSHOT_LIST_IDS Listing all snapshot ids
2018-07-11 21:20:04.113 TRACE SNAPSHOT_LIST_REVISIONS Listing revisions for snapshot backup
2018-07-11 21:20:04.198 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/backup/1 from the snapshot cache
2018-07-11 21:20:04.239 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/backup/2 from the snapshot cache
2018-07-11 21:20:04.285 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/backup/3 from the snapshot cache
2018-07-11 21:20:04.326 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/backup/4 from the snapshot cache
2018-07-11 21:20:04.367 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/backup/5 from the snapshot cache
2018-07-11 21:20:04.409 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/backup/6 from the snapshot cache
2018-07-11 21:20:04.410 DEBUG SNAPSHOT_DELETE Snapshot backup at revision 2 to be deleted - older than 1 days, less than 1 days from previous
2018-07-11 21:20:04.410 INFO SNAPSHOT_DELETE Deleting snapshot backup at revision 2
2018-07-11 21:20:04.424 DEBUG CHUNK_CACHE Chunk 1b3bdb3229746baa88efe5c48cf6189fbe572e863d63ab56fb2679ab580b579a has been loaded from the snapshot cache
2018-07-11 21:20:04.444 DEBUG DOWNLOAD_FETCH Fetching chunk 1ce42d419b9ecaef78f4760bd5180443084fa7eca8e8c6eba174ea3a8ba1fe6f
2018-07-11 21:20:04.445 DEBUG CHUNK_CACHE Chunk 1ce42d419b9ecaef78f4760bd5180443084fa7eca8e8c6eba174ea3a8ba1fe6f has been loaded from the snapshot cache
2018-07-11 21:20:04.447 DEBUG DOWNLOAD_FETCH Fetching chunk 7c3f4844cd94b75c0b969257775b7bc2fb1a132c9d93446a350ff088f99d2b2c
2018-07-11 21:20:04.452 DEBUG CHUNK_CACHE Chunk 7c3f4844cd94b75c0b969257775b7bc2fb1a132c9d93446a350ff088f99d2b2c has been loaded from the snapshot cache
2018-07-11 21:20:04.572 DEBUG DOWNLOAD_FETCH Fetching chunk 54ea3d5845e7687fef56a098199a8db2950c1c7d1796754dcae341b82d83b5f2
2018-07-11 21:20:04.577 DEBUG CHUNK_CACHE Chunk 54ea3d5845e7687fef56a098199a8db2950c1c7d1796754dcae341b82d83b5f2 has been loaded from the snapshot cache
2018-07-11 21:20:04.579 DEBUG DOWNLOAD_FETCH Fetching chunk a14efa66b126ee24aa13ea39960eca7a4b710a128d898c9ddffce5d57f3b3a2d
2018-07-11 21:20:04.580 DEBUG CHUNK_CACHE Chunk a14efa66b126ee24aa13ea39960eca7a4b710a128d898c9ddffce5d57f3b3a2d has been loaded from the snapshot cache
2018-07-11 21:20:04.684 DEBUG DOWNLOAD_FETCH Fetching chunk 54ea3d5845e7687fef56a098199a8db2950c1c7d1796754dcae341b82d83b5f2
2018-07-11 21:20:04.689 DEBUG CHUNK_CACHE Chunk 54ea3d5845e7687fef56a098199a8db2950c1c7d1796754dcae341b82d83b5f2 has been loaded from the snapshot cache
2018-07-11 21:20:04.689 DEBUG DOWNLOAD_FETCH Fetching chunk 2bceac3d48bef096404bfe4a7c4645701603b9738198fdae0c867d6d4ea6a3ff
2018-07-11 21:20:04.690 DEBUG CHUNK_CACHE Chunk 2bceac3d48bef096404bfe4a7c4645701603b9738198fdae0c867d6d4ea6a3ff has been loaded from the snapshot cache
2018-07-11 21:20:04.794 DEBUG DOWNLOAD_FETCH Fetching chunk 54ea3d5845e7687fef56a098199a8db2950c1c7d1796754dcae341b82d83b5f2
2018-07-11 21:20:04.799 DEBUG CHUNK_CACHE Chunk 54ea3d5845e7687fef56a098199a8db2950c1c7d1796754dcae341b82d83b5f2 has been loaded from the snapshot cache
2018-07-11 21:20:04.800 DEBUG DOWNLOAD_FETCH Fetching chunk ccf9a9c0085d1cf160f6437c71a47f3b6e6560d501ec049d232038a44ff6f6d8
2018-07-11 21:20:04.800 DEBUG CHUNK_CACHE Chunk ccf9a9c0085d1cf160f6437c71a47f3b6e6560d501ec049d232038a44ff6f6d8 has been loaded from the snapshot cache
2018-07-11 21:20:05.192 ERROR CHUNK_DELETE Failed to fossilize the chunk 515b226b6f533991a99884759bd428e46a1d36aa66aca71897490e95ded33a70: 404 Not Found
```
[prune.log](https://github.com/gilbertchen/duplicacy/files/2186780/prune.log)

### PR DESCRIPTION
**Pull request by jtackaberry**
Fixes #458

### CODE REVIEW

**Comment by markfeit** [comment]
See my [comment](https://github.com/gilbertchen/duplicacy/issues/458#issuecomment-404486725) in #458.

**Comment by gilbertchen** [comment]
Thank you for the fix!

**Comment by jcmaco** [comment]
Has this patch made it into the Windows 2.1.1 binary? I'm getting the same error in my logs with Wasabi as my storage URL. I've checked and that the chunk file is in my Wasabi bucket.
`ERROR Failed to fossilize the chunk [removed hash]: 404 Not Found`

**Comment by magikmw** [comment]
@jcmaco I'm also getting this error with 2.1.2 cli. Did you happen to find a fix?

**Comment by markfeit** [comment]
I'm not running 2.1.2 yet but will try to get upgraded and check out the problem when a get some time to do it.  (And if nobody beats me to it...)

**Pull request merged**
