### PR TITLE
Standardize scale of stats units

### PR DESCRIPTION
**Pull request by fracai**
reformat results of PrettyNumber and added GiB range to PrettySize
added SI suffixes to each

as discussed in #435

### CODE REVIEW

**Comment by fracai** [comment]
I note that PrettySize and PrettyNumber are very similar. Is it worth combining them? Or should they stay separate with their differences?

**Comment by fracai** [comment]
Good point, I've removed the 'B' suffix from each. I looked at each of their uses and I think it makes sense now. Let me know if you want any adjustments. Specifically, an alternate change would be to put the 'B' back in and adjust each use of the methods to remove the redundant 'bytes'.

**Comment by jt70471** [comment]
I have not applied this patch yet, but seems the numbers will be left with K/M/G/T or Ki/Mi/Gi/Ti suffixes... shouldn't they all end with B? i.e. KiB, MiB, GiB, TiB, etc?

**Comment by fracai** [comment]
Yes, @gilbertchen suggested that the 'B' could be problematic given that other spots in the code supply 'bytes'. I'm thinking I should take another look at this to add the 'B' back in and remove 'bytes' where applicable from the code.

**Comment by jt70471** [comment]
The standard is KiB and KB, etc. so I think it would be best to stick to the standard and remove "bytes" anywhere is it found after the PrettyNumber or PrettySize formatted number.

**Comment by fracai** [comment]
Yeah, that's what I'm headed for

**Comment by fracai** [comment]
The additional commit restores the "B" and reformats the log messages so there isn't any duplicate "bytes" phrasing.

**Comment by gilbertchen** [comment]
I don't like separating `B` and `ytes` in different locations.  Format strings like ``Files: %d total, %sytes; %d new, %sytes` look awkward.

May I suggest using K/M/G/T only and then the format strings can use either `%sB` or `%s bytes`?

**Comment by fracai** [comment]
yes, I'll make that change in a few hours.

**Comment by fracai** [comment]
I think I've covered all the relevant format strings. I moved the "B" out of the PrettyNumber and PrettySize methods and put "B" in the relevant format strings.

**Comment by jt70471** [comment]
Thanks for all of your work, but I really don't like MiBytes, GiBytes, etc.. Never seen the Bytes written out like that in any other usage, I would prefer just plain old MB, MiB, GB, GiB, etc.

**Comment by fracai** [comment]
I'm fairly neutral with how the units are expressed. At this point I think it's whatever @gilbertchen wants. :-)

**Comment by gilbertchen** [comment]
I'm closing this PR without merging it.  The notions of Ki, Mi, Gi, etc would be in conflict with the input where we use `-c 1M` or `-c 128K` to specify the chunk size in the `init` and `add` command.  Although technically KiB, MiB and GiB are more correct, it seems K, M, G are ok and generally acceptable.  Therefore I want to leave these as they are now.

**Pull request closed without merging**
