### PR TITLE
Add APFS snapshot support

### PR DESCRIPTION
**Pull request by amarcu5**
Add's VSS support for macOS using APFS snapshot

Addresses issue #341

### CODE REVIEW

**Comment by jt70471** [comment]
I haven't patched my copy yet, but will do so and test. Thanks for doing this, too bad Apple has decided to make the API for APFS snapshots so convoluted to use. The API itself seems simple, minus the criterial for the special entitlement...

**Comment by amarcu5** [comment]
@jt70471 All done, thanks, I'd forgotten about that

**Comment by amarcu5** [comment]
@jt70471 agreed, keep the suggestions coming!

While I was at it I noticed I inadvertently broke Windows builds but all fixed now

**Comment by jt70471** [comment]
This looks great, the only thing I couldn't test was the check that the filesystem is indeed APFS, because I have already converted all of my macs to APFS!

**Comment by gilbertchen** [comment]
Thanks for your contribution and testing!  I can't test it myself but if it has been running good for you guys that it should be safe to merge it.

**Pull request merged**
