### PR TITLE
spelling fix, go fmt, go vet

### PR DESCRIPTION
**Pull request by mikecook**

### CODE REVIEW

**Comment by mikecook** [comment]
@gilbertchen is there anything else I need to do to get this merged? This fixes some unreachable code paths.

**Comment by TheBestPessimist** [comment]
I don't think you have to do anything, it's just that he's busy with polishing the new web gui: https://forum.duplicacy.com/t/feedback-on-duplicacy-web-edition-beta-releases/1470/62

**Comment by gilbertchen** [comment]
Sorry for no response.  I'll process all these PRs after the web gui is released.

**Comment by gilbertchen** [comment]
Thank you for the changes!

**Pull request merged**
